import { TableSchemaSpec } from '../types/erp';

export const ALL_TABLE_SCHEMAS: TableSchemaSpec[] = [
  {
    sheetName: 'Company_Settings',
    description: 'Master company metadata, contact information, and business parameters.',
    columns: [
      {
        sheetName: 'Company_Settings',
        columnName: 'Setting_ID',
        dataType: 'Text',
        isPrimaryKey: true,
        required: true,
        initialValue: 'SET-001',
        validIf: '',
        suggestedFormula: '',
        appSheetType: 'Text',
      },
      {
        sheetName: 'Company_Settings',
        columnName: 'Company_Name',
        dataType: 'Text',
        isPrimaryKey: false,
        required: true,
        initialValue: 'Hayat Haven Enterprise',
        validIf: 'ISNOTBLANK([_THIS])',
        suggestedFormula: '',
        appSheetType: 'Text',
      },
      {
        sheetName: 'Company_Settings',
        columnName: 'Business_Type',
        dataType: 'Enum',
        isPrimaryKey: false,
        required: true,
        initialValue: 'Retail + Wholesale',
        validIf: 'LIST("Retail", "Wholesale", "Retail + Wholesale")',
        suggestedFormula: '',
        appSheetType: 'Enum',
      },
      {
        sheetName: 'Company_Settings',
        columnName: 'Currency',
        dataType: 'Text',
        isPrimaryKey: false,
        required: true,
        initialValue: 'BDT',
        validIf: '',
        suggestedFormula: '',
        appSheetType: 'Text',
      },
      {
        sheetName: 'Company_Settings',
        columnName: 'Country',
        dataType: 'Text',
        isPrimaryKey: false,
        required: true,
        initialValue: 'Bangladesh',
        validIf: '',
        suggestedFormula: '',
        appSheetType: 'Text',
      },
      {
        sheetName: 'Company_Settings',
        columnName: 'Logo_URL',
        dataType: 'Image/URL',
        isPrimaryKey: false,
        required: false,
        initialValue: '',
        validIf: '',
        suggestedFormula: '',
        appSheetType: 'Image',
      },
      {
        sheetName: 'Company_Settings',
        columnName: 'Address',
        dataType: 'LongText',
        isPrimaryKey: false,
        required: true,
        initialValue: 'House 42, Road 11, Banani, Dhaka-1213',
        validIf: '',
        suggestedFormula: '',
        appSheetType: 'LongText',
      },
      {
        sheetName: 'Company_Settings',
        columnName: 'Phone',
        dataType: 'Phone',
        isPrimaryKey: false,
        required: true,
        initialValue: '+880 1711-000000',
        validIf: '',
        suggestedFormula: '',
        appSheetType: 'Phone',
      },
      {
        sheetName: 'Company_Settings',
        columnName: 'Email',
        dataType: 'Email',
        isPrimaryKey: false,
        required: true,
        initialValue: 'info@hayathaven.com',
        validIf: '',
        suggestedFormula: '',
        appSheetType: 'Email',
      },
      {
        sheetName: 'Company_Settings',
        columnName: 'Tax_BIN_ID',
        dataType: 'Text',
        isPrimaryKey: false,
        required: false,
        initialValue: 'BIN-1002938481',
        validIf: '',
        suggestedFormula: '',
        appSheetType: 'Text',
      },
      {
        sheetName: 'Company_Settings',
        columnName: 'Bank_Details',
        dataType: 'LongText',
        isPrimaryKey: false,
        required: false,
        initialValue: 'Dutch-Bangla Bank, Banani Branch, A/C: 110-120-998877',
        validIf: '',
        suggestedFormula: '',
        appSheetType: 'LongText',
      },
      {
        sheetName: 'Company_Settings',
        columnName: 'Terms_Conditions',
        dataType: 'LongText',
        isPrimaryKey: false,
        required: false,
        initialValue: 'Goods once sold cannot be returned after 7 days.',
        validIf: '',
        suggestedFormula: '',
        appSheetType: 'LongText',
      },
    ],
  },
  {
    sheetName: 'Dashboard',
    description: 'Executive KPI metrics, summary calculations, and system status.',
    columns: [
      { sheetName: 'Dashboard', columnName: 'Metric_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'MTR-1', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Dashboard', columnName: 'Total_Sales_BDT', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Sales_Orders[Grand_Total])', appSheetType: 'Price' },
      { sheetName: 'Dashboard', columnName: 'Total_Purchases_BDT', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Purchases[Grand_Total])', appSheetType: 'Price' },
      { sheetName: 'Dashboard', columnName: 'Total_Customer_Due', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Customers[Current_Balance])', appSheetType: 'Price' },
      { sheetName: 'Dashboard', columnName: 'Total_Supplier_Due', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Suppliers[Current_Balance])', appSheetType: 'Price' },
      { sheetName: 'Dashboard', columnName: 'Total_Expenses', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Expenses[Amount])', appSheetType: 'Price' },
      { sheetName: 'Dashboard', columnName: 'Net_Profit', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Total_Sales_BDT] - [Total_Purchases_BDT] - [Total_Expenses]', appSheetType: 'Price' },
      { sheetName: 'Dashboard', columnName: 'Low_Stock_Alert_Count', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'COUNT(SELECT(Products[Product_ID], [Current_Stock] <= [Low_Stock_Alert]))', appSheetType: 'Number' },
    ],
  },
  {
    sheetName: 'Customers',
    description: 'Master list of retail and wholesale clients, contact information, credit limits and balances.',
    columns: [
      { sheetName: 'Customers', columnName: 'Customer_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Customers', columnName: 'Customer_Name', dataType: 'Text', isPrimaryKey: false, required: true, initialValue: '', validIf: 'ISNOTBLANK([_THIS])', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Customers', columnName: 'Phone', dataType: 'Phone', isPrimaryKey: false, required: true, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Phone' },
      { sheetName: 'Customers', columnName: 'Email', dataType: 'Email', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Email' },
      { sheetName: 'Customers', columnName: 'Address', dataType: 'LongText', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'LongText' },
      { sheetName: 'Customers', columnName: 'Customer_Type', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Retail', validIf: 'LIST("Retail", "Wholesale")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Customers', columnName: 'Credit_Limit', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '50000', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Customers', columnName: 'Opening_Balance', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Customers', columnName: 'Current_Balance', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Opening_Balance] + SUM(SELECT(Sales_Orders[Due_Amount], [Customer_ID] = [_THISROW].[Customer_ID])) - SUM(SELECT(Customer_Payments[Amount], [Customer_ID] = [_THISROW].[Customer_ID]))', appSheetType: 'Price' },
      { sheetName: 'Customers', columnName: 'Status', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Active', validIf: 'LIST("Active", "Inactive")', suggestedFormula: '', appSheetType: 'Enum' },
    ],
  },
  {
    sheetName: 'Suppliers',
    description: 'Master list of vendor partners, manufacturers, contact representatives and payable balances.',
    columns: [
      { sheetName: 'Suppliers', columnName: 'Supplier_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Suppliers', columnName: 'Supplier_Name', dataType: 'Text', isPrimaryKey: false, required: true, initialValue: '', validIf: 'ISNOTBLANK([_THIS])', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Suppliers', columnName: 'Contact_Person', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Suppliers', columnName: 'Phone', dataType: 'Phone', isPrimaryKey: false, required: true, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Phone' },
      { sheetName: 'Suppliers', columnName: 'Email', dataType: 'Email', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Email' },
      { sheetName: 'Suppliers', columnName: 'Address', dataType: 'LongText', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'LongText' },
      { sheetName: 'Suppliers', columnName: 'Opening_Balance', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Suppliers', columnName: 'Current_Balance', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Opening_Balance] + SUM(SELECT(Purchases[Due_Amount], [Supplier_ID] = [_THISROW].[Supplier_ID])) - SUM(SELECT(Supplier_Payments[Amount], [Supplier_ID] = [_THISROW].[Supplier_ID]))', appSheetType: 'Price' },
      { sheetName: 'Suppliers', columnName: 'Status', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Active', validIf: 'LIST("Active", "Inactive")', suggestedFormula: '', appSheetType: 'Enum' },
    ],
  },
  {
    sheetName: 'Categories',
    description: 'Product category taxonomy classification.',
    columns: [
      { sheetName: 'Categories', columnName: 'Category_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Categories', columnName: 'Category_Name', dataType: 'Text', isPrimaryKey: false, required: true, initialValue: '', validIf: 'ISNOTBLANK([_THIS])', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Categories', columnName: 'Description', dataType: 'LongText', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'LongText' },
      { sheetName: 'Categories', columnName: 'Status', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Active', validIf: 'LIST("Active", "Inactive")', suggestedFormula: '', appSheetType: 'Enum' },
    ],
  },
  {
    sheetName: 'Brands',
    description: 'Product brand classification and origin.',
    columns: [
      { sheetName: 'Brands', columnName: 'Brand_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Brands', columnName: 'Brand_Name', dataType: 'Text', isPrimaryKey: false, required: true, initialValue: '', validIf: 'ISNOTBLANK([_THIS])', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Brands', columnName: 'Country_Of_Origin', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: 'Bangladesh', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Brands', columnName: 'Status', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Active', validIf: 'LIST("Active", "Inactive")', suggestedFormula: '', appSheetType: 'Enum' },
    ],
  },
  {
    sheetName: 'Products',
    description: 'Master stock inventory items, pricing, barcodes, images, units and stock alert thresholds.',
    columns: [
      { sheetName: 'Products', columnName: 'Product_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Products', columnName: 'Barcode', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Products', columnName: 'Image_URL', dataType: 'Image/URL', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Image' },
      { sheetName: 'Products', columnName: 'Product_Name', dataType: 'Text', isPrimaryKey: false, required: true, initialValue: '', validIf: 'ISNOTBLANK([_THIS])', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Products', columnName: 'Category_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Categories.Category_ID', refRelationship: 'Categories', isPartOfRelationship: false, required: true, initialValue: '', validIf: 'Categories[Category_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Products', columnName: 'Brand_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Brands.Brand_ID', refRelationship: 'Brands', isPartOfRelationship: false, required: true, initialValue: '', validIf: 'Brands[Brand_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Products', columnName: 'Unit', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Pcs', validIf: 'LIST("Pcs", "Kg", "Box", "Ctn", "Mtr", "Set")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Products', columnName: 'Size', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: 'Standard', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Products', columnName: 'Buying_Price', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Products', columnName: 'Selling_Price', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= [Buying_Price]', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Products', columnName: 'Min_Selling_Price', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= [Buying_Price]', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Products', columnName: 'Opening_Stock', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Number' },
      { sheetName: 'Products', columnName: 'Current_Stock', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Opening_Stock] + SUM(SELECT(Purchase_Items[Quantity], [Product_ID] = [_THISROW].[Product_ID])) - SUM(SELECT(Sales_Order_Items[Quantity], [Product_ID] = [_THISROW].[Product_ID]))', appSheetType: 'Number' },
      { sheetName: 'Products', columnName: 'Low_Stock_Alert', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '10', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Number' },
      { sheetName: 'Products', columnName: 'Status', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Active', validIf: 'LIST("Active", "Discontinued")', suggestedFormula: '', appSheetType: 'Enum' },
    ],
  },
  {
    sheetName: 'Sales_Orders',
    description: 'Header record for retail and wholesale customer sales orders.',
    columns: [
      { sheetName: 'Sales_Orders', columnName: 'Order_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Sales_Orders', columnName: 'Order_Date', dataType: 'Date', isPrimaryKey: false, required: true, initialValue: 'TODAY()', validIf: '', suggestedFormula: '', appSheetType: 'Date' },
      { sheetName: 'Sales_Orders', columnName: 'Customer_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Customers.Customer_ID', refRelationship: 'Customers', isPartOfRelationship: false, required: true, initialValue: '', validIf: 'Customers[Customer_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Sales_Orders', columnName: 'Order_Type', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Retail', validIf: 'LIST("Retail", "Wholesale")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Sales_Orders', columnName: 'Subtotal', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM([Related Sales_Order_Items][Total_Price])', appSheetType: 'Price' },
      { sheetName: 'Sales_Orders', columnName: 'Discount_Amount', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Sales_Orders', columnName: 'Delivery_Charge', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Sales_Orders', columnName: 'Grand_Total', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Subtotal] - [Discount_Amount] + [Delivery_Charge]', appSheetType: 'Price' },
      { sheetName: 'Sales_Orders', columnName: 'Advance_Paid', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Sales_Orders', columnName: 'Due_Amount', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Grand_Total] - [Advance_Paid]', appSheetType: 'Price' },
      { sheetName: 'Sales_Orders', columnName: 'Payment_Status', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Unpaid', validIf: 'LIST("Paid", "Partial", "Unpaid")', suggestedFormula: 'IFS([Due_Amount] <= 0, "Paid", [Advance_Paid] > 0, "Partial", TRUE, "Unpaid")', appSheetType: 'Enum' },
      { sheetName: 'Sales_Orders', columnName: 'Delivery_Status', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Pending', validIf: 'LIST("Pending", "Processing", "Delivered", "Cancelled")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Sales_Orders', columnName: 'Notes', dataType: 'LongText', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'LongText' },
      { sheetName: 'Sales_Orders', columnName: 'Created_By', dataType: 'Text', isPrimaryKey: false, required: true, initialValue: 'USEREMAIL()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
    ],
  },
  {
    sheetName: 'Sales_Order_Items',
    description: 'Line item breakdown attached to Sales_Orders header (IsPartOf=TRUE).',
    columns: [
      { sheetName: 'Sales_Order_Items', columnName: 'Item_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Sales_Order_Items', columnName: 'Order_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Sales_Orders.Order_ID', refRelationship: 'Sales_Orders', isPartOfRelationship: true, required: true, initialValue: '', validIf: 'Sales_Orders[Order_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Sales_Order_Items', columnName: 'Product_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Products.Product_ID', refRelationship: 'Products', isPartOfRelationship: false, required: true, initialValue: '', validIf: 'Products[Product_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Sales_Order_Items', columnName: 'Quantity', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '1', validIf: '[_THIS] > 0', suggestedFormula: '', appSheetType: 'Number' },
      { sheetName: 'Sales_Order_Items', columnName: 'Unit_Price', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= [Product_ID].[Buying_Price]', suggestedFormula: '[Product_ID].[Selling_Price]', appSheetType: 'Price' },
      { sheetName: 'Sales_Order_Items', columnName: 'Total_Price', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Quantity] * [Unit_Price]', appSheetType: 'Price' },
      { sheetName: 'Sales_Order_Items', columnName: 'Profit_Amount', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Total_Price] - ([Quantity] * [Product_ID].[Buying_Price])', appSheetType: 'Price' },
    ],
  },
  {
    sheetName: 'Purchases',
    description: 'Header record for supplier procurement and purchase orders.',
    columns: [
      { sheetName: 'Purchases', columnName: 'Purchase_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Purchases', columnName: 'Purchase_Date', dataType: 'Date', isPrimaryKey: false, required: true, initialValue: 'TODAY()', validIf: '', suggestedFormula: '', appSheetType: 'Date' },
      { sheetName: 'Purchases', columnName: 'Supplier_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Suppliers.Supplier_ID', refRelationship: 'Suppliers', isPartOfRelationship: false, required: true, initialValue: '', validIf: 'Suppliers[Supplier_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Purchases', columnName: 'Invoice_Number', dataType: 'Text', isPrimaryKey: false, required: true, initialValue: '', validIf: 'ISNOTBLANK([_THIS])', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Purchases', columnName: 'Subtotal', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM([Related Purchase_Items][Total_Cost])', appSheetType: 'Price' },
      { sheetName: 'Purchases', columnName: 'Discount_Amount', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Purchases', columnName: 'Transport_Cost', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Purchases', columnName: 'Grand_Total', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Subtotal] - [Discount_Amount] + [Transport_Cost]', appSheetType: 'Price' },
      { sheetName: 'Purchases', columnName: 'Paid_Amount', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Purchases', columnName: 'Due_Amount', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Grand_Total] - [Paid_Amount]', appSheetType: 'Price' },
      { sheetName: 'Purchases', columnName: 'Payment_Status', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Unpaid', validIf: 'LIST("Paid", "Partial", "Unpaid")', suggestedFormula: 'IFS([Due_Amount] <= 0, "Paid", [Paid_Amount] > 0, "Partial", TRUE, "Unpaid")', appSheetType: 'Enum' },
      { sheetName: 'Purchases', columnName: 'Status', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Received', validIf: 'LIST("Received", "Pending", "Cancelled")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Purchases', columnName: 'Notes', dataType: 'LongText', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'LongText' },
    ],
  },
  {
    sheetName: 'Purchase_Items',
    description: 'Line item breakdown attached to Purchases header (IsPartOf=TRUE). Auto-increases stock.',
    columns: [
      { sheetName: 'Purchase_Items', columnName: 'Item_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Purchase_Items', columnName: 'Purchase_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Purchases.Purchase_ID', refRelationship: 'Purchases', isPartOfRelationship: true, required: true, initialValue: '', validIf: 'Purchases[Purchase_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Purchase_Items', columnName: 'Product_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Products.Product_ID', refRelationship: 'Products', isPartOfRelationship: false, required: true, initialValue: '', validIf: 'Products[Product_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Purchase_Items', columnName: 'Quantity', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '1', validIf: '[_THIS] > 0', suggestedFormula: '', appSheetType: 'Number' },
      { sheetName: 'Purchase_Items', columnName: 'Unit_Cost', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '[Product_ID].[Buying_Price]', appSheetType: 'Price' },
      { sheetName: 'Purchase_Items', columnName: 'Total_Cost', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Quantity] * [Unit_Cost]', appSheetType: 'Price' },
    ],
  },
  {
    sheetName: 'Customer_Payments',
    description: 'Record of collections and money received from customers.',
    columns: [
      { sheetName: 'Customer_Payments', columnName: 'Payment_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Customer_Payments', columnName: 'Payment_Date', dataType: 'Date', isPrimaryKey: false, required: true, initialValue: 'TODAY()', validIf: '', suggestedFormula: '', appSheetType: 'Date' },
      { sheetName: 'Customer_Payments', columnName: 'Customer_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Customers.Customer_ID', refRelationship: 'Customers', isPartOfRelationship: false, required: true, initialValue: '', validIf: 'Customers[Customer_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Customer_Payments', columnName: 'Order_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Sales_Orders.Order_ID', refRelationship: 'Sales_Orders', isPartOfRelationship: false, required: false, initialValue: '', validIf: 'Sales_Orders[Order_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Customer_Payments', columnName: 'Payment_Method', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Cash', validIf: 'LIST("Cash", "bKash", "Nagad", "Bank Transfer", "Card")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Customer_Payments', columnName: 'Amount', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] > 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Customer_Payments', columnName: 'Reference_No', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Customer_Payments', columnName: 'Notes', dataType: 'LongText', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'LongText' },
    ],
  },
  {
    sheetName: 'Supplier_Payments',
    description: 'Record of disbursements and payments made to vendors.',
    columns: [
      { sheetName: 'Supplier_Payments', columnName: 'Payment_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Supplier_Payments', columnName: 'Payment_Date', dataType: 'Date', isPrimaryKey: false, required: true, initialValue: 'TODAY()', validIf: '', suggestedFormula: '', appSheetType: 'Date' },
      { sheetName: 'Supplier_Payments', columnName: 'Supplier_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Suppliers.Supplier_ID', refRelationship: 'Suppliers', isPartOfRelationship: false, required: true, initialValue: '', validIf: 'Suppliers[Supplier_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Supplier_Payments', columnName: 'Purchase_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Purchases.Purchase_ID', refRelationship: 'Purchases', isPartOfRelationship: false, required: false, initialValue: '', validIf: 'Purchases[Purchase_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Supplier_Payments', columnName: 'Payment_Method', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Cash', validIf: 'LIST("Cash", "bKash", "Nagad", "Bank Transfer", "Card")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Supplier_Payments', columnName: 'Amount', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] > 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Supplier_Payments', columnName: 'Reference_No', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Supplier_Payments', columnName: 'Notes', dataType: 'LongText', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'LongText' },
    ],
  },
  {
    sheetName: 'Expenses',
    description: 'Operational overhead expenses, rent, salaries, utilities and logistics cost tracking.',
    columns: [
      { sheetName: 'Expenses', columnName: 'Expense_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Expenses', columnName: 'Expense_Date', dataType: 'Date', isPrimaryKey: false, required: true, initialValue: 'TODAY()', validIf: '', suggestedFormula: '', appSheetType: 'Date' },
      { sheetName: 'Expenses', columnName: 'Category', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Misc', validIf: 'LIST("Rent", "Utilities", "Salary", "Transport", "Marketing", "Maintenance", "Misc")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Expenses', columnName: 'Amount', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] > 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Expenses', columnName: 'Payment_Method', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Cash', validIf: 'LIST("Cash", "bKash", "Nagad", "Bank Transfer")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Expenses', columnName: 'Description', dataType: 'Text', isPrimaryKey: false, required: true, initialValue: '', validIf: 'ISNOTBLANK([_THIS])', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Expenses', columnName: 'Reference_No', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
    ],
  },
  {
    sheetName: 'Stock_Movement',
    description: 'Audit log of all physical stock transactions, IN, OUT, returns and manual stock adjustments.',
    columns: [
      { sheetName: 'Stock_Movement', columnName: 'Movement_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Stock_Movement', columnName: 'Movement_Date', dataType: 'DateTime', isPrimaryKey: false, required: true, initialValue: 'NOW()', validIf: '', suggestedFormula: '', appSheetType: 'DateTime' },
      { sheetName: 'Stock_Movement', columnName: 'Product_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Products.Product_ID', refRelationship: 'Products', isPartOfRelationship: false, required: true, initialValue: '', validIf: 'Products[Product_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Stock_Movement', columnName: 'Type', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Stock IN', validIf: 'LIST("Stock IN", "Stock OUT", "Adjustment", "Return")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Stock_Movement', columnName: 'Quantity', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '1', validIf: '[_THIS] != 0', suggestedFormula: '', appSheetType: 'Number' },
      { sheetName: 'Stock_Movement', columnName: 'Previous_Stock', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '', appSheetType: 'Number' },
      { sheetName: 'Stock_Movement', columnName: 'New_Stock', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '', appSheetType: 'Number' },
      { sheetName: 'Stock_Movement', columnName: 'Reference_Type', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Manual Adjustment', validIf: 'LIST("Sales Order", "Purchase", "Manual Adjustment")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Stock_Movement', columnName: 'Reference_ID', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Stock_Movement', columnName: 'Remarks', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
    ],
  },
  {
    sheetName: 'Customer_Ledger',
    description: 'Statement of account log for each customer showing debit (invoiced) and credit (paid) history.',
    columns: [
      { sheetName: 'Customer_Ledger', columnName: 'Entry_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Customer_Ledger', columnName: 'Date', dataType: 'Date', isPrimaryKey: false, required: true, initialValue: 'TODAY()', validIf: '', suggestedFormula: '', appSheetType: 'Date' },
      { sheetName: 'Customer_Ledger', columnName: 'Customer_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Customers.Customer_ID', refRelationship: 'Customers', isPartOfRelationship: false, required: true, initialValue: '', validIf: 'Customers[Customer_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Customer_Ledger', columnName: 'Transaction_Type', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Sales Invoice', validIf: 'LIST("Sales Invoice", "Payment Received", "Opening Balance", "Adjustment")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Customer_Ledger', columnName: 'Reference_ID', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Customer_Ledger', columnName: 'Debit', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Customer_Ledger', columnName: 'Credit', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Customer_Ledger', columnName: 'Balance', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '', appSheetType: 'Price' },
    ],
  },
  {
    sheetName: 'Supplier_Ledger',
    description: 'Statement of account log for each supplier showing debit (paid) and credit (invoiced) history.',
    columns: [
      { sheetName: 'Supplier_Ledger', columnName: 'Entry_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Supplier_Ledger', columnName: 'Date', dataType: 'Date', isPrimaryKey: false, required: true, initialValue: 'TODAY()', validIf: '', suggestedFormula: '', appSheetType: 'Date' },
      { sheetName: 'Supplier_Ledger', columnName: 'Supplier_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Suppliers.Supplier_ID', refRelationship: 'Suppliers', isPartOfRelationship: false, required: true, initialValue: '', validIf: 'Suppliers[Supplier_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Supplier_Ledger', columnName: 'Transaction_Type', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'Purchase Invoice', validIf: 'LIST("Purchase Invoice", "Payment Made", "Opening Balance", "Adjustment")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'Supplier_Ledger', columnName: 'Reference_ID', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Supplier_Ledger', columnName: 'Debit', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Supplier_Ledger', columnName: 'Credit', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '[_THIS] >= 0', suggestedFormula: '', appSheetType: 'Price' },
      { sheetName: 'Supplier_Ledger', columnName: 'Balance', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '', appSheetType: 'Price' },
    ],
  },
  {
    sheetName: 'Profit_Report',
    description: 'Financial profit & loss statement calculations (Gross Sales - COGS - Expenses = Net Profit).',
    columns: [
      { sheetName: 'Profit_Report', columnName: 'Period_Month', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'TEXT(TODAY(), "YYYY-MM")', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Profit_Report', columnName: 'Total_Sales', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Sales_Orders[Grand_Total])', appSheetType: 'Price' },
      { sheetName: 'Profit_Report', columnName: 'Total_COGS', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Sales_Order_Items[Quantity] * Sales_Order_Items[Product_ID].[Buying_Price])', appSheetType: 'Price' },
      { sheetName: 'Profit_Report', columnName: 'Gross_Profit', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Total_Sales] - [Total_COGS]', appSheetType: 'Price' },
      { sheetName: 'Profit_Report', columnName: 'Total_Expenses', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Expenses[Amount])', appSheetType: 'Price' },
      { sheetName: 'Profit_Report', columnName: 'Net_Profit', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Gross_Profit] - [Total_Expenses]', appSheetType: 'Price' },
    ],
  },
  {
    sheetName: 'Sales_Report',
    description: 'Summary and analytical breakdown of sales performance by date, type, and channel.',
    columns: [
      { sheetName: 'Sales_Report', columnName: 'Report_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Sales_Report', columnName: 'Report_Date', dataType: 'Date', isPrimaryKey: false, required: true, initialValue: 'TODAY()', validIf: '', suggestedFormula: '', appSheetType: 'Date' },
      { sheetName: 'Sales_Report', columnName: 'Total_Orders_Count', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'COUNT(Sales_Orders[Order_ID])', appSheetType: 'Number' },
      { sheetName: 'Sales_Report', columnName: 'Retail_Sales_BDT', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(SELECT(Sales_Orders[Grand_Total], [Order_Type] = "Retail"))', appSheetType: 'Price' },
      { sheetName: 'Sales_Report', columnName: 'Wholesale_Sales_BDT', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(SELECT(Sales_Orders[Grand_Total], [Order_Type] = "Wholesale"))', appSheetType: 'Price' },
      { sheetName: 'Sales_Report', columnName: 'Total_Discount_Given', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Sales_Orders[Discount_Amount])', appSheetType: 'Price' },
      { sheetName: 'Sales_Report', columnName: 'Total_Collection', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Sales_Orders[Advance_Paid]) + SUM(Customer_Payments[Amount])', appSheetType: 'Price' },
    ],
  },
  {
    sheetName: 'Purchase_Report',
    description: 'Summary breakdown of supplier orders, payments made, and pending payables.',
    columns: [
      { sheetName: 'Purchase_Report', columnName: 'Report_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Purchase_Report', columnName: 'Report_Date', dataType: 'Date', isPrimaryKey: false, required: true, initialValue: 'TODAY()', validIf: '', suggestedFormula: '', appSheetType: 'Date' },
      { sheetName: 'Purchase_Report', columnName: 'Total_Purchase_Orders', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'COUNT(Purchases[Purchase_ID])', appSheetType: 'Number' },
      { sheetName: 'Purchase_Report', columnName: 'Total_Purchase_Amount', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Purchases[Grand_Total])', appSheetType: 'Price' },
      { sheetName: 'Purchase_Report', columnName: 'Total_Paid_To_Suppliers', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Purchases[Paid_Amount]) + SUM(Supplier_Payments[Amount])', appSheetType: 'Price' },
      { sheetName: 'Purchase_Report', columnName: 'Total_Supplier_Due', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Purchases[Due_Amount])', appSheetType: 'Price' },
    ],
  },
  {
    sheetName: 'Stock_Report',
    description: 'Warehouse inventory valuation report at buying price and retail selling price.',
    columns: [
      { sheetName: 'Stock_Report', columnName: 'Report_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Stock_Report', columnName: 'Total_Product_SKUs', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'COUNT(Products[Product_ID])', appSheetType: 'Number' },
      { sheetName: 'Stock_Report', columnName: 'Total_Stock_Quantity', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Products[Current_Stock])', appSheetType: 'Number' },
      { sheetName: 'Stock_Report', columnName: 'Valuation_At_Cost', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Products[Current_Stock] * Products[Buying_Price])', appSheetType: 'Price' },
      { sheetName: 'Stock_Report', columnName: 'Valuation_At_Retail', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Products[Current_Stock] * Products[Selling_Price])', appSheetType: 'Price' },
      { sheetName: 'Stock_Report', columnName: 'Low_Stock_Items_Count', dataType: 'Number', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'COUNT(SELECT(Products[Product_ID], [Current_Stock] <= [Low_Stock_Alert]))', appSheetType: 'Number' },
    ],
  },
  {
    sheetName: 'Due_Report',
    description: 'Outstanding customer receivables aging and supplier payables summary.',
    columns: [
      { sheetName: 'Due_Report', columnName: 'Report_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Due_Report', columnName: 'Total_Customer_Receivable', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Customers[Current_Balance])', appSheetType: 'Price' },
      { sheetName: 'Due_Report', columnName: 'Total_Supplier_Payable', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: 'SUM(Suppliers[Current_Balance])', appSheetType: 'Price' },
      { sheetName: 'Due_Report', columnName: 'Net_Working_Capital', dataType: 'Decimal', isPrimaryKey: false, required: true, initialValue: '0', validIf: '', suggestedFormula: '[Total_Customer_Receivable] - [Total_Supplier_Payable]', appSheetType: 'Price' },
    ],
  },
  {
    sheetName: 'Invoice_Print',
    description: 'Print layout formatting and dynamic template mapping for A4 printable invoices.',
    columns: [
      { sheetName: 'Invoice_Print', columnName: 'Print_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'UNIQUEID()', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Invoice_Print', columnName: 'Order_ID', dataType: 'Ref', isPrimaryKey: false, foreignKeys: 'Sales_Orders.Order_ID', refRelationship: 'Sales_Orders', isPartOfRelationship: false, required: true, initialValue: '', validIf: 'Sales_Orders[Order_ID]', suggestedFormula: '', appSheetType: 'Ref' },
      { sheetName: 'Invoice_Print', columnName: 'Invoice_Title', dataType: 'Text', isPrimaryKey: false, required: true, initialValue: 'TAX INVOICE', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'Invoice_Print', columnName: 'Print_Date', dataType: 'DateTime', isPrimaryKey: false, required: true, initialValue: 'NOW()', validIf: '', suggestedFormula: '', appSheetType: 'DateTime' },
      { sheetName: 'Invoice_Print', columnName: 'PDF_File_Path', dataType: 'File', isPrimaryKey: false, required: false, initialValue: '', validIf: '', suggestedFormula: 'CONCATENATE("Invoices/", [Order_ID], ".pdf")', appSheetType: 'File' },
    ],
  },
  {
    sheetName: 'App_Settings',
    description: 'AppSheet automation bots, webhook configs, PDF templates, and WhatsApp notification parameters.',
    columns: [
      { sheetName: 'App_Settings', columnName: 'Config_ID', dataType: 'Text', isPrimaryKey: true, required: true, initialValue: 'CFG-001', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'App_Settings', columnName: 'Bot_Name', dataType: 'Text', isPrimaryKey: false, required: true, initialValue: 'Auto Stock Update & PDF Invoice Bot', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'App_Settings', columnName: 'Trigger_Event', dataType: 'Enum', isPrimaryKey: false, required: true, initialValue: 'ADDS_AND_UPDATES', validIf: 'LIST("ADDS_ONLY", "UPDATES_ONLY", "ADDS_AND_UPDATES")', suggestedFormula: '', appSheetType: 'Enum' },
      { sheetName: 'App_Settings', columnName: 'WhatsApp_API_Key', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: 'WA_KEY_ENV', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
      { sheetName: 'App_Settings', columnName: 'WhatsApp_Message_Template', dataType: 'LongText', isPrimaryKey: false, required: false, initialValue: 'Dear <<[Customer_ID].[Customer_Name]>>, your order <<[Order_ID]>> of BDT <<[Grand_Total]>> is confirmed.', validIf: '', suggestedFormula: '', appSheetType: 'LongText' },
      { sheetName: 'App_Settings', columnName: 'AppSheet_App_ID', dataType: 'Text', isPrimaryKey: false, required: false, initialValue: 'HayatHavenEnterprise-18651801599', validIf: '', suggestedFormula: '', appSheetType: 'Text' },
    ],
  },
];
